In [1]:
# DERIVED FROM https://versenotes.org/a-list-of-books-in-the-bible-by-number-of-chapters/ FILES
# RUN 'esv.py' FIRST
import pandas as pd

esv_books = pd.read_csv('ESV/ESV Books.csv').set_index('Book')
esv_chapters = pd.read_csv('ESV/ESV Chapters.csv').set_index('Reference')
esv_verses = pd.read_csv('ESV/ESV Verses.csv').set_index('Reference')
esv_books

,Chapters,Verses,Words,Vs/Ch,Wd/Ch,Wd/Vs,Time (150 WPM),Time (200 WPM),Time (250 WPM)
Book,,,,,,,,,
Genesis,50,1533,36397,30.7,727.9,23.7,4hr 2m,3hr 1m,2hr 25m
Exodus,40,1213,31005,30.3,775.1,25.6,3hr 26m,2hr 35m,2hr 4m
Leviticus,27,859,23493,31.8,870.1,27.3,2hr 36m,1hr 57m,1hr 33m
Numbers,36,1288,31043,35.8,862.3,24.1,3hr 26m,2hr 35m,2hr 4m
Deuteronomy,34,959,27618,28.2,812.3,28.8,3hr 4m,2hr 18m,1hr 50m
...,...,...,...,...,...,...,...,...,...
1 John,5,105,2507,21.0,501.4,23.9,16m 42s,12m 32s,10m 1s
2 John,1,13,302,13.0,302.0,23.2,2m 0s,1m 30s,1m 12s
3 John,1,15,303,15.0,303.0,20.2,2m 1s,1m 30s,1m 12s
Jude,1,25,610,25.0,610.0,24.4,4m 4s,3m 3s,2m 26s
Revelation,22,404,11526,18.4,523.9,28.5,1hr 16m,57m 37s,46m 6s

In [2]:
esv_chapters

,Verses,Words,Wd/Vs,Time (150 WPM),Time (200 WPM),Time (250 WPM)
Reference,,,,,,
Genesis 1,31,791,25.5,5m 16s,3m 57s,3m 9s
Genesis 2,25,639,25.6,4m 15s,3m 11s,2m 33s
Genesis 3,24,683,28.5,4m 33s,3m 24s,2m 43s
Genesis 4,26,594,22.8,3m 57s,2m 58s,2m 22s
Genesis 5,32,427,13.3,2m 50s,2m 8s,1m 42s
...,...,...,...,...,...,...
Revelation 18,24,713,29.7,4m 45s,3m 33s,2m 51s
Revelation 19,21,633,30.1,4m 13s,3m 9s,2m 31s
Revelation 20,15,493,32.9,3m 17s,2m 27s,1m 58s
Revelation 21,27,688,25.5,4m 35s,3m 26s,2m 45s
Revelation 22,21,549,26.1,3m 39s,2m 44s,2m 11s

In [3]:
esv_verses

                  Words
Reference
Genesis 1:1          10
Genesis 1:2          29
Genesis 1:3          11
Genesis 1:4          16
Genesis 1:5          22
...                 ...
Revelation 22:17     35
Revelation 22:18     29
Revelation 22:19     36
Revelation 22:20     16
Revelation 22:21     10

[31074 rows x 1 columns]

In [4]:
for book, data in esv_books.iterrows():
    print(f'{book} ({data['Chapters']} Chapters | {data['Verses']:,} Verses | {data['Words']:,} Words)')

Genesis (50 Chapters | 1,533 Verses | 36,397 Words)
Exodus (40 Chapters | 1,213 Verses | 31,005 Words)
Leviticus (27 Chapters | 859 Verses | 23,493 Words)
Numbers (36 Chapters | 1,288 Verses | 31,043 Words)
Deuteronomy (34 Chapters | 959 Verses | 27,618 Words)
Joshua (24 Chapters | 658 Verses | 17,993 Words)
Judges (21 Chapters | 618 Verses | 18,312 Words)
Ruth (4 Chapters | 85 Verses | 2,437 Words)
1 Samuel (31 Chapters | 810 Verses | 24,168 Words)
2 Samuel (24 Chapters | 695 Verses | 19,795 Words)
1 Kings (22 Chapters | 816 Verses | 23,520 Words)
2 Kings (25 Chapters | 719 Verses | 22,912 Words)
1 Chronicles (29 Chapters | 942 Verses | 18,580 Words)
2 Chronicles (36 Chapters | 822 Verses | 24,856 Words)
Ezra (10 Chapters | 280 Verses | 6,921 Words)
Nehemiah (13 Chapters | 406 Verses | 9,874 Words)
Esther (10 Chapters | 167 Verses | 5,484 Words)
Job (42 Chapters | 1,070 Verses | 17,627 Words)
Psalms (150 Chapters | 2,461 Verses | 41,273 Words)
Proverbs (31 Chapters | 915 Verses | 14,552 Words)
Ecclesiastes (12 Chapters | 222 Verses | 5,376 Words)
Song of Solomon (8 Chapters | 117 Verses | 2,576 Words)
Isaiah (66 Chapters | 1,292 Verses | 35,385 Words)
Jeremiah (52 Chapters | 1,364 Verses | 40,544 Words)
Lamentations (5 Chapters | 154 Verses | 3,253 Words)
Ezekiel (48 Chapters | 1,273 Verses | 37,309 Words)
Daniel (12 Chapters | 357 Verses | 11,272 Words)
Hosea (14 Chapters | 197 Verses | 4,976 Words)
Joel (3 Chapters | 73 Verses | 1,917 Words)
Amos (9 Chapters | 146 Verses | 4,067 Words)
Obadiah (1 Chapters | 21 Verses | 614 Words)
Jonah (4 Chapters | 48 Verses | 1,312 Words)
Micah (7 Chapters | 105 Verses | 3,022 Words)
Nahum (3 Chapters | 47 Verses | 1,111 Words)
Habakkuk (3 Chapters | 56 Verses | 1,373 Words)
Zephaniah (3 Chapters | 53 Verses | 1,573 Words)
Haggai (2 Chapters | 38 Verses | 1,095 Words)
Zechariah (14 Chapters | 211 Verses | 6,083 Words)
Malachi (4 Chapters | 55 Verses | 1,752 Words)
Matthew (28 Chapters | 1,067 Verses | 23,019 Words)
Mark (16 Chapters | 673 Verses | 14,596 Words)
Luke (24 Chapters | 1,149 Verses | 25,010 Words)
John (21 Chapters | 866 Verses | 18,841 Words)
Acts (28 Chapters | 1,003 Verses | 23,633 Words)
Romans (16 Chapters | 432 Verses | 9,530 Words)
1 Corinthians (16 Chapters | 437 Verses | 9,314 Words)
2 Corinthians (13 Chapters | 257 Verses | 6,077 Words)
Galatians (6 Chapters | 149 Verses | 3,133 Words)
Ephesians (6 Chapters | 155 Verses | 3,014 Words)
Philippians (4 Chapters | 104 Verses | 2,160 Words)
Colossians (4 Chapters | 95 Verses | 1,950 Words)
1 Thessalonians (5 Chapters | 89 Verses | 1,854 Words)
2 Thessalonians (3 Chapters | 47 Verses | 1,065 Words)
1 Timothy (6 Chapters | 113 Verses | 2,314 Words)
2 Timothy (4 Chapters | 83 Verses | 1,647 Words)
Titus (3 Chapters | 46 Verses | 928 Words)
Philemon (1 Chapters | 25 Verses | 461 Words)
Hebrews (13 Chapters | 303 Verses | 6,935 Words)
James (5 Chapters | 108 Verses | 2,331 Words)
1 Peter (5 Chapters | 105 Verses | 2,405 Words)
2 Peter (3 Chapters | 61 Verses | 1,549 Words)
1 John (5 Chapters | 105 Verses | 2,507 Words)
2 John (1 Chapters | 13 Verses | 302 Words)
3 John (1 Chapters | 15 Verses | 303 Words)
Jude (1 Chapters | 25 Verses | 610 Words)
Revelation (22 Chapters | 404 Verses | 11,526 Words)

In [5]:
for book, data in esv_books.iterrows():
    print(f'<p>{book}</p>')
    print(f'<p class="sub-p">({data['Chapters']} Chapters | {data['Verses']:,} Verses | {data['Words']:,} Words)</p>')

<p>Genesis</p>
<p class="sub-p">(50 Chapters | 1,533 Verses | 36,397 Words)</p>
<p>Exodus</p>
<p class="sub-p">(40 Chapters | 1,213 Verses | 31,005 Words)</p>
<p>Leviticus</p>
<p class="sub-p">(27 Chapters | 859 Verses | 23,493 Words)</p>
<p>Numbers</p>
<p class="sub-p">(36 Chapters | 1,288 Verses | 31,043 Words)</p>
<p>Deuteronomy</p>
<p class="sub-p">(34 Chapters | 959 Verses | 27,618 Words)</p>
<p>Joshua</p>
<p class="sub-p">(24 Chapters | 658 Verses | 17,993 Words)</p>
<p>Judges</p>
<p class="sub-p">(21 Chapters | 618 Verses | 18,312 Words)</p>
<p>Ruth</p>
<p class="sub-p">(4 Chapters | 85 Verses | 2,437 Words)</p>
<p>1 Samuel</p>
<p class="sub-p">(31 Chapters | 810 Verses | 24,168 Words)</p>
<p>2 Samuel</p>
<p class="sub-p">(24 Chapters | 695 Verses | 19,795 Words)</p>
<p>1 Kings</p>
<p class="sub-p">(22 Chapters | 816 Verses | 23,520 Words)</p>
<p>2 Kings</p>
<p class="sub-p">(25 Chapters | 719 Verses | 22,912 Words)</p>
<p>1 Chronicles</p>
<p class="sub-p">(29 Chapters | 942 Verses | 18,580 Words)</p>
<p>2 Chronicles</p>
<p class="sub-p">(36 Chapters | 822 Verses | 24,856 Words)</p>
<p>Ezra</p>
<p class="sub-p">(10 Chapters | 280 Verses | 6,921 Words)</p>
<p>Nehemiah</p>
<p class="sub-p">(13 Chapters | 406 Verses | 9,874 Words)</p>
<p>Esther</p>
<p class="sub-p">(10 Chapters | 167 Verses | 5,484 Words)</p>
<p>Job</p>
<p class="sub-p">(42 Chapters | 1,070 Verses | 17,627 Words)</p>
<p>Psalms</p>
<p class="sub-p">(150 Chapters | 2,461 Verses | 41,273 Words)</p>
<p>Proverbs</p>
<p class="sub-p">(31 Chapters | 915 Verses | 14,552 Words)</p>
<p>Ecclesiastes</p>
<p class="sub-p">(12 Chapters | 222 Verses | 5,376 Words)</p>
<p>Song of Solomon</p>
<p class="sub-p">(8 Chapters | 117 Verses | 2,576 Words)</p>
<p>Isaiah</p>
<p class="sub-p">(66 Chapters | 1,292 Verses | 35,385 Words)</p>
<p>Jeremiah</p>
<p class="sub-p">(52 Chapters | 1,364 Verses | 40,544 Words)</p>
<p>Lamentations</p>
<p class="sub-p">(5 Chapters | 154 Verses | 3,253 Words)</p>
<p>Ezekiel</p>
<p class="sub-p">(48 Chapters | 1,273 Verses | 37,309 Words)</p>
<p>Daniel</p>
<p class="sub-p">(12 Chapters | 357 Verses | 11,272 Words)</p>
<p>Hosea</p>
<p class="sub-p">(14 Chapters | 197 Verses | 4,976 Words)</p>
<p>Joel</p>
<p class="sub-p">(3 Chapters | 73 Verses | 1,917 Words)</p>
<p>Amos</p>
<p class="sub-p">(9 Chapters | 146 Verses | 4,067 Words)</p>
<p>Obadiah</p>
<p class="sub-p">(1 Chapters | 21 Verses | 614 Words)</p>
<p>Jonah</p>
<p class="sub-p">(4 Chapters | 48 Verses | 1,312 Words)</p>
<p>Micah</p>
<p class="sub-p">(7 Chapters | 105 Verses | 3,022 Words)</p>
<p>Nahum</p>
<p class="sub-p">(3 Chapters | 47 Verses | 1,111 Words)</p>
<p>Habakkuk</p>
<p class="sub-p">(3 Chapters | 56 Verses | 1,373 Words)</p>
<p>Zephaniah</p>
<p class="sub-p">(3 Chapters | 53 Verses | 1,573 Words)</p>
<p>Haggai</p>
<p class="sub-p">(2 Chapters | 38 Verses | 1,095 Words)</p>
<p>Zechariah</p>
<p class="sub-p">(14 Chapters | 211 Verses | 6,083 Words)</p>
<p>Malachi</p>
<p class="sub-p">(4 Chapters | 55 Verses | 1,752 Words)</p>
<p>Matthew</p>
<p class="sub-p">(28 Chapters | 1,067 Verses | 23,019 Words)</p>
<p>Mark</p>
<p class="sub-p">(16 Chapters | 673 Verses | 14,596 Words)</p>
<p>Luke</p>
<p class="sub-p">(24 Chapters | 1,149 Verses | 25,010 Words)</p>
<p>John</p>
<p class="sub-p">(21 Chapters | 866 Verses | 18,841 Words)</p>
<p>Acts</p>
<p class="sub-p">(28 Chapters | 1,003 Verses | 23,633 Words)</p>
<p>Romans</p>
<p class="sub-p">(16 Chapters | 432 Verses | 9,530 Words)</p>
<p>1 Corinthians</p>
<p class="sub-p">(16 Chapters | 437 Verses | 9,314 Words)</p>
<p>2 Corinthians</p>
<p class="sub-p">(13 Chapters | 257 Verses | 6,077 Words)</p>
<p>Galatians</p>
<p class="sub-p">(6 Chapters | 149 Verses | 3,133 Words)</p>
<p>Ephesians</p>
<p class="sub-p">(6 Chapters | 155 Verses | 3,014 Words)</p>
<p>Philippians</p>
<p class="sub-p">(4 Chapters | 104 Verses | 2,160 Words)</p>
<p>Colossians</p>
<p class="sub-p">(4 Chapters | 95 Verses | 1,950 Words)</p>
<p>1 Thessalonians</p>
<p class="sub-p">(5 Chapters | 89 Verses | 1,854 Words)</p>
<p>2 Thessalonians</p>
<p class="sub-p">(3 Chapters | 47 Verses | 1,065 Words)</p>
<p>1 Timothy</p>
<p class="sub-p">(6 Chapters | 113 Verses | 2,314 Words)</p>
<p>2 Timothy</p>
<p class="sub-p">(4 Chapters | 83 Verses | 1,647 Words)</p>
<p>Titus</p>
<p class="sub-p">(3 Chapters | 46 Verses | 928 Words)</p>
<p>Philemon</p>
<p class="sub-p">(1 Chapters | 25 Verses | 461 Words)</p>
<p>Hebrews</p>
<p class="sub-p">(13 Chapters | 303 Verses | 6,935 Words)</p>
<p>James</p>
<p class="sub-p">(5 Chapters | 108 Verses | 2,331 Words)</p>
<p>1 Peter</p>
<p class="sub-p">(5 Chapters | 105 Verses | 2,405 Words)</p>
<p>2 Peter</p>
<p class="sub-p">(3 Chapters | 61 Verses | 1,549 Words)</p>
<p>1 John</p>
<p class="sub-p">(5 Chapters | 105 Verses | 2,507 Words)</p>
<p>2 John</p>
<p class="sub-p">(1 Chapters | 13 Verses | 302 Words)</p>
<p>3 John</p>
<p class="sub-p">(1 Chapters | 15 Verses | 303 Words)</p>
<p>Jude</p>
<p class="sub-p">(1 Chapters | 25 Verses | 610 Words)</p>
<p>Revelation</p>
<p class="sub-p">(22 Chapters | 404 Verses | 11,526 Words)</p>