In [1]:
# DERIVED FROM https://versenotes.org/a-list-of-books-in-the-bible-by-number-of-chapters/ FILES
# RUN 'esv.py' FIRST
from bible_stats import BibleStats # My Custom Class for the WPM Function & Constants
import pandas as pd

esv_books = pd.read_csv('ESV/ESV Books.csv').set_index('Book')
reading_times = [f'Time ({word_count} WPM)' for word_count in range(BibleStats.MIN_WPM, BibleStats.MAX_WPM, BibleStats.INCREMENT)]
esv_books.drop(reading_times, axis=1, inplace=True)
esv_books.drop(['Vs/Ch', 'Wd/Ch', 'Wd/Vs'], axis=1, inplace=True)
esv_books

             Chapters  Verses  Words
Book
Genesis            50    1533  36397
Exodus             40    1213  31005
Leviticus          27     859  23493
Numbers            36    1288  31043
Deuteronomy        34     959  27618
...               ...     ...    ...
1 John              5     105   2507
2 John              1      13    302
3 John              1      15    303
Jude                1      25    610
Revelation         22     404  11526

[66 rows x 3 columns]

In [2]:
bk = esv_books.rename(columns={'Chapters': 'c', 'Verses': 'v', 'Words': 'w'})
sections = [
    {'S': 'Bible', 'B': 66, 'C': bk.sum()['c'], 'V': bk.sum()['v'], 'W': bk.sum()['w']},
    {'S': 'Old Testament', 'B': 39, 'C': bk.iloc[:39].sum()['c'], 'V': bk.iloc[:39].sum()['v'], 'W': bk.iloc[:39].sum()['w']},
    {'S': 'New Testament', 'B': 27, 'C': bk.iloc[39:].sum()['c'], 'V': bk.iloc[39:].sum()['v'], 'W': bk.iloc[39:].sum()['w']},
    {'S': 'Pentateuch', 'B': 5, 'C': bk.iloc[0:5].sum()['c'], 'V': bk.iloc[0:5].sum()['v'], 'W': bk.iloc[0:5].sum()['w']},
    {'S': 'History', 'B': 12, 'C': bk.iloc[5:17].sum()['c'], 'V': bk.iloc[5:17].sum()['v'], 'W': bk.iloc[5:17].sum()['w']},
    {'S': 'Poetry', 'B': 5, 'C': bk.iloc[17:22].sum()['c'], 'V': bk.iloc[17:22].sum()['v'], 'W': bk.iloc[17:22].sum()['w']},
    {'S': 'Major Prophets', 'B': 5, 'C': bk.iloc[22:27].sum()['c'], 'V': bk.iloc[22:27].sum()['v'], 'W': bk.iloc[22:27].sum()['w']},
    {'S': 'Minor Prophets', 'B': 12, 'C': bk.iloc[27:39].sum()['c'], 'V': bk.iloc[27:39].sum()['v'], 'W': bk.iloc[27:39].sum()['w']},
    {'S': 'Gospels', 'B': 4, 'C': bk.iloc[39:43].sum()['c'], 'V': bk.iloc[39:43].sum()['v'], 'W': bk.iloc[39:43].sum()['w']},
    {'S': 'History (Acts)', 'B': 1, 'C': bk.iloc[43:44].sum()['c'], 'V': bk.iloc[43:44].sum()['v'], 'W': bk.iloc[43:44].sum()['w']},
    {'S': 'Pauline Epistles', 'B': 13, 'C': bk.iloc[44:57].sum()['c'], 'V': bk.iloc[44:57].sum()['v'], 'W': bk.iloc[44:57].sum()['w']},
    {'S': 'General Epistles', 'B': 8, 'C': bk.iloc[57:65].sum()['c'], 'V': bk.iloc[57:65].sum()['v'], 'W': bk.iloc[57:65].sum()['w']},
    {'S': 'Apocalypse (Revelation)', 'B': 1, 'C': bk.iloc[65:].sum()['c'], 'V': bk.iloc[65:].sum()['v'], 'W': bk.iloc[65:].sum()['w']},
]
esv_sections = pd.DataFrame(sections)
esv_sections.rename(columns={'S': 'Section', 'B': 'Books', 'C': 'Chapters', 'V': 'Verses', 'W': 'Words'}, inplace=True)
esv_sections.set_index('Section', inplace=True)
esv_sections.to_csv('ESV/Raw ESV Sections.csv')
esv_sections

                         Books  Chapters  Verses   Words
Section
Bible                       66      1189   31074  759484
Old Testament               39       929   23145  582470
New Testament               27       260    7929  177014
Pentateuch                   5       187    5852  149556
History                     12       249    7018  194852
Poetry                       5       243    4785   81404
Major Prophets               5       183    4440  127763
Minor Prophets              12        67    1050   28895
Gospels                      4        89    3755   81466
History (Acts)               1        28    1003   23633
Pauline Epistles            13        87    2032   43447
General Epistles             8        34     735   16942
Apocalypse (Revelation)      1        22     404   11526

In [3]:
sections_df = pd.read_csv('ESV/Raw ESV Sections.csv').set_index('Section')

sections_df['Ch/Book'] = round(sections_df['Chapters'] / sections_df['Books'], 1)
sections_df['Vs/Book'] = round(sections_df['Verses'] / sections_df['Books'], 1)
sections_df['Wd/Book'] = round(sections_df['Words'] / sections_df['Books']).astype('int')

sections_df['Vs/Ch'] = round(sections_df['Verses'] / sections_df['Chapters'], 1)
sections_df['Wd/Ch'] = round(sections_df['Words'] / sections_df['Chapters'], 1)
sections_df['Wd/Vs'] = round(sections_df['Words'] / sections_df['Verses'], 1)

for time in range(BibleStats.MIN_WPM, BibleStats.MAX_WPM, BibleStats.INCREMENT):
    sections_df[f'Time ({time} WPM)'] = sections_df['Words'].apply(lambda x: BibleStats.wpm(x, time))

sections_df.to_csv('ESV/ESV Sections.csv')
sections_df

,Books,Chapters,Verses,Words,Ch/Book,Vs/Book,Wd/Book,Vs/Ch,Wd/Ch,Wd/Vs,Time (150 WPM),Time (200 WPM),Time (250 WPM)
Section,,,,,,,,,,,,,
Bible,66,1189,31074,759484,18.0,470.8,11507,26.1,638.8,24.4,84hr 23m,63hr 17m,50hr 37m
Old Testament,39,929,23145,582470,23.8,593.5,14935,24.9,627.0,25.2,64hr 43m,48hr 32m,38hr 49m
New Testament,27,260,7929,177014,9.6,293.7,6556,30.5,680.8,22.3,19hr 40m,14hr 45m,11hr 48m
Pentateuch,5,187,5852,149556,37.4,1170.4,29911,31.3,799.8,25.6,16hr 37m,12hr 27m,9hr 58m
History,12,249,7018,194852,20.8,584.8,16238,28.2,782.5,27.8,21hr 39m,16hr 14m,12hr 59m
Poetry,5,243,4785,81404,48.6,957.0,16281,19.7,335.0,17.0,9hr 2m,6hr 47m,5hr 25m
Major Prophets,5,183,4440,127763,36.6,888.0,25553,24.3,698.2,28.8,14hr 11m,10hr 38m,8hr 31m
Minor Prophets,12,67,1050,28895,5.6,87.5,2408,15.7,431.3,27.5,3hr 12m,2hr 24m,1hr 55m
Gospels,4,89,3755,81466,22.2,938.8,20366,42.2,915.3,21.7,9hr 3m,6hr 47m,5hr 25m
History (Acts),1,28,1003,23633,28.0,1003.0,23633,35.8,844.0,23.6,2hr 37m,1hr 58m,1hr 34m
Pauline Epistles,13,87,2032,43447,6.7,156.3,3342,23.4,499.4,21.4,4hr 49m,3hr 37m,2hr 53m
General Epistles,8,34,735,16942,4.2,91.9,2118,21.6,498.3,23.1,1hr 52m,1hr 24m,1hr 7m
Apocalypse (Revelation),1,22,404,11526,22.0,404.0,11526,18.4,523.9,28.5,1hr 16m,57m 37s,46m 6s

In [4]:
for section, data in esv_sections.iterrows():
    print(f'{section}: ({data['Books']} Books | {data['Chapters']:,} Chapters | {data['Verses']:,} Verses | {data['Words']:,} Words)')

Bible: (66 Books | 1,189 Chapters | 31,074 Verses | 759,484 Words)
Old Testament: (39 Books | 929 Chapters | 23,145 Verses | 582,470 Words)
New Testament: (27 Books | 260 Chapters | 7,929 Verses | 177,014 Words)
Pentateuch: (5 Books | 187 Chapters | 5,852 Verses | 149,556 Words)
History: (12 Books | 249 Chapters | 7,018 Verses | 194,852 Words)
Poetry: (5 Books | 243 Chapters | 4,785 Verses | 81,404 Words)
Major Prophets: (5 Books | 183 Chapters | 4,440 Verses | 127,763 Words)
Minor Prophets: (12 Books | 67 Chapters | 1,050 Verses | 28,895 Words)
Gospels: (4 Books | 89 Chapters | 3,755 Verses | 81,466 Words)
History (Acts): (1 Books | 28 Chapters | 1,003 Verses | 23,633 Words)
Pauline Epistles: (13 Books | 87 Chapters | 2,032 Verses | 43,447 Words)
General Epistles: (8 Books | 34 Chapters | 735 Verses | 16,942 Words)
Apocalypse (Revelation): (1 Books | 22 Chapters | 404 Verses | 11,526 Words)

In [5]:
for section, data in esv_sections.iterrows():
    print(f'<h3>{section}:</h3>')
    print(f'<p class="sub-p">({data['Books']} Books | {data['Chapters']:,} Chapters | {data['Verses']:,} Verses | <nobr>{data['Words']:,} Words)</nobr></p>')
    print()

<h3>Bible:</h3>
<p class="sub-p">(66 Books | 1,189 Chapters | 31,074 Verses | <nobr>759,484 Words)</nobr></p>

<h3>Old Testament:</h3>
<p class="sub-p">(39 Books | 929 Chapters | 23,145 Verses | <nobr>582,470 Words)</nobr></p>

<h3>New Testament:</h3>
<p class="sub-p">(27 Books | 260 Chapters | 7,929 Verses | <nobr>177,014 Words)</nobr></p>

<h3>Pentateuch:</h3>
<p class="sub-p">(5 Books | 187 Chapters | 5,852 Verses | <nobr>149,556 Words)</nobr></p>

<h3>History:</h3>
<p class="sub-p">(12 Books | 249 Chapters | 7,018 Verses | <nobr>194,852 Words)</nobr></p>

<h3>Poetry:</h3>
<p class="sub-p">(5 Books | 243 Chapters | 4,785 Verses | <nobr>81,404 Words)</nobr></p>

<h3>Major Prophets:</h3>
<p class="sub-p">(5 Books | 183 Chapters | 4,440 Verses | <nobr>127,763 Words)</nobr></p>

<h3>Minor Prophets:</h3>
<p class="sub-p">(12 Books | 67 Chapters | 1,050 Verses | <nobr>28,895 Words)</nobr></p>

<h3>Gospels:</h3>
<p class="sub-p">(4 Books | 89 Chapters | 3,755 Verses | <nobr>81,466 Words)</nobr></p>

<h3>History (Acts):</h3>
<p class="sub-p">(1 Books | 28 Chapters | 1,003 Verses | <nobr>23,633 Words)</nobr></p>

<h3>Pauline Epistles:</h3>
<p class="sub-p">(13 Books | 87 Chapters | 2,032 Verses | <nobr>43,447 Words)</nobr></p>

<h3>General Epistles:</h3>
<p class="sub-p">(8 Books | 34 Chapters | 735 Verses | <nobr>16,942 Words)</nobr></p>

<h3>Apocalypse (Revelation):</h3>
<p class="sub-p">(1 Books | 22 Chapters | 404 Verses | <nobr>11,526 Words)</nobr></p>