In [1]:
# DERIVED FROM https://versenotes.org/a-list-of-books-in-the-bible-by-number-of-chapters/ FILES
# RUN 'esv.py' & 'esv_sections.ipynb' FIRST
from bible_stats import BibleStats # My Custom Class for the WPM Function & Constants
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

WPM_SPEED = 300

esv_sections = pd.read_csv('ESV/ESV Sections.csv').set_index('Section')
esv_books = pd.read_csv('ESV/ESV Books.csv').set_index('Book')
esv_chapters = pd.read_csv('ESV/ESV Chapters.csv').set_index('Reference')

def wpm(word_count: int):
    time = word_count / WPM_SPEED
    hrs, mins, secs = int(time // 60), int(time % 60), int(float(time * 60) % 60)
    return f'{hrs}hr {mins}m' if hrs > 0 else f'{mins}m {secs}s'

reading_times = [f'Time ({word_count} WPM)' for word_count in range(BibleStats.MIN_WPM, BibleStats.MAX_WPM, BibleStats.INCREMENT)]
esv_sections.drop(reading_times, axis=1, inplace=True)
esv_books.drop(reading_times, axis=1, inplace=True)
esv_chapters.drop(reading_times, axis=1, inplace=True)

esv_sections[f'Time ({WPM_SPEED} WPM)'] = esv_sections['Words'].apply(lambda x: wpm(x))
esv_books[f'Time ({WPM_SPEED} WPM)'] = esv_books['Words'].apply(lambda x: wpm(x))
esv_chapters[f'Time ({WPM_SPEED} WPM)'] = esv_chapters['Words'].apply(lambda x: wpm(x))
esv_sections

,Books,Chapters,Verses,Words,Ch/Book,Vs/Book,Wd/Book,Vs/Ch,Wd/Ch,Wd/Vs,Time (300 WPM)
Section,,,,,,,,,,,
Bible,66,1189,31074,759484,18.0,470.8,11507,26.1,638.8,24.4,42hr 11m
Old Testament,39,929,23145,582470,23.8,593.5,14935,24.9,627.0,25.2,32hr 21m
New Testament,27,260,7929,177014,9.6,293.7,6556,30.5,680.8,22.3,9hr 50m
Pentateuch,5,187,5852,149556,37.4,1170.4,29911,31.3,799.8,25.6,8hr 18m
History,12,249,7018,194852,20.8,584.8,16238,28.2,782.5,27.8,10hr 49m
Poetry,5,243,4785,81404,48.6,957.0,16281,19.7,335.0,17.0,4hr 31m
Major Prophets,5,183,4440,127763,36.6,888.0,25553,24.3,698.2,28.8,7hr 5m
Minor Prophets,12,67,1050,28895,5.6,87.5,2408,15.7,431.3,27.5,1hr 36m
Gospels,4,89,3755,81466,22.2,938.8,20366,42.2,915.3,21.7,4hr 31m
History (Acts),1,28,1003,23633,28.0,1003.0,23633,35.8,844.0,23.6,1hr 18m
Pauline Epistles,13,87,2032,43447,6.7,156.3,3342,23.4,499.4,21.4,2hr 24m
General Epistles,8,34,735,16942,4.2,91.9,2118,21.6,498.3,23.1,56m 28s
Apocalypse (Revelation),1,22,404,11526,22.0,404.0,11526,18.4,523.9,28.5,38m 25s

In [2]:
esv_books

                 Chapters  Verses  Words  Vs/Ch   Wd/Ch  Wd/Vs Time (300 WPM)
Book
Genesis                50    1533  36397   30.7   727.9   23.7         2hr 1m
Exodus                 40    1213  31005   30.3   775.1   25.6        1hr 43m
Leviticus              27     859  23493   31.8   870.1   27.3        1hr 18m
Numbers                36    1288  31043   35.8   862.3   24.1        1hr 43m
Deuteronomy            34     959  27618   28.2   812.3   28.8        1hr 32m
Joshua                 24     658  17993   27.4   749.7   27.3        59m 58s
Judges                 21     618  18312   29.4   872.0   29.6         1hr 1m
Ruth                    4      85   2437   21.2   609.2   28.7          8m 7s
1 Samuel               31     810  24168   26.1   779.6   29.8        1hr 20m
2 Samuel               24     695  19795   29.0   824.8   28.5         1hr 5m
1 Kings                22     816  23520   37.1  1069.1   28.8        1hr 18m
2 Kings                25     719  22912   28.8   916.5   31.9        1hr 16m
1 Chronicles           29     942  18580   32.5   640.7   19.7         1hr 1m
2 Chronicles           36     822  24856   22.8   690.4   30.2        1hr 22m
Ezra                   10     280   6921   28.0   692.1   24.7         23m 4s
Nehemiah               13     406   9874   31.2   759.5   24.3        32m 54s
Esther                 10     167   5484   16.7   548.4   32.8        18m 16s
Job                    42    1070  17627   25.5   419.7   16.5        58m 45s
Psalms                150    2461  41273   16.4   275.2   16.8        2hr 17m
Proverbs               31     915  14552   29.5   469.4   15.9        48m 30s
Ecclesiastes           12     222   5376   18.5   448.0   24.2        17m 55s
Song of Solomon         8     117   2576   14.6   322.0   22.0         8m 35s
Isaiah                 66    1292  35385   19.6   536.1   27.4        1hr 57m
Jeremiah               52    1364  40544   26.2   779.7   29.7        2hr 15m
Lamentations            5     154   3253   30.8   650.6   21.1        10m 50s
Ezekiel                48    1273  37309   26.5   777.3   29.3         2hr 4m
Daniel                 12     357  11272   29.8   939.3   31.6        37m 34s
Hosea                  14     197   4976   14.1   355.4   25.3        16m 35s
Joel                    3      73   1917   24.3   639.0   26.3         6m 23s
Amos                    9     146   4067   16.2   451.9   27.9        13m 33s
Obadiah                 1      21    614   21.0   614.0   29.2          2m 2s
Jonah                   4      48   1312   12.0   328.0   27.3         4m 22s
Micah                   7     105   3022   15.0   431.7   28.8         10m 4s
Nahum                   3      47   1111   15.7   370.3   23.6         3m 42s
Habakkuk                3      56   1373   18.7   457.7   24.5         4m 34s
Zephaniah               3      53   1573   17.7   524.3   29.7         5m 14s
Haggai                  2      38   1095   19.0   547.5   28.8         3m 39s
Zechariah              14     211   6083   15.1   434.5   28.8        20m 16s
Malachi                 4      55   1752   13.8   438.0   31.9         5m 50s
Matthew                28    1067  23019   38.1   822.1   21.6        1hr 16m
Mark                   16     673  14596   42.1   912.2   21.7        48m 39s
Luke                   24    1149  25010   47.9  1042.1   21.8        1hr 23m
John                   21     866  18841   41.2   897.2   21.8         1hr 2m
Acts                   28    1003  23633   35.8   844.0   23.6        1hr 18m
Romans                 16     432   9530   27.0   595.6   22.1        31m 46s
1 Corinthians          16     437   9314   27.3   582.1   21.3         31m 2s
2 Corinthians          13     257   6077   19.8   467.5   23.6        20m 15s
Galatians               6     149   3133   24.8   522.2   21.0        10m 26s
Ephesians               6     155   3014   25.8   502.3   19.4         10m 2s
Philippians             4     104   2160   26.0   540.0   20.8         7m 12s
Colossians              4      95   1950   23.8   487.5   20.5         6m 30s
1 Thessalonians         5      89   1854   17.8   370.8   20.8         6m 10s
2 Thessalonians         3      47   1065   15.7   355.0   22.7         3m 33s
1 Timothy               6     113   2314   18.8   385.7   20.5         7m 42s
2 Timothy               4      83   1647   20.8   411.8   19.8         5m 29s
Titus                   3      46    928   15.3   309.3   20.2          3m 5s
Philemon                1      25    461   25.0   461.0   18.4         1m 32s
Hebrews                13     303   6935   23.3   533.5   22.9         23m 7s
James                   5     108   2331   21.6   466.2   21.6         7m 46s
1 Peter                 5     105   2405   21.0   481.0   22.9          8m 1s
2 Peter                 3      61   1549   20.3   516.3   25.4          5m 9s
1 John                  5     105   2507   21.0   501.4   23.9         8m 21s
2 John                  1      13    302   13.0   302.0   23.2          1m 0s
3 John                  1      15    303   15.0   303.0   20.2          1m 0s
Jude                    1      25    610   25.0   610.0   24.4          2m 2s
Revelation             22     404  11526   18.4   523.9   28.5        38m 25s

In [3]:
esv_chapters

                   Verses  Words  Wd/Vs Time (300 WPM)
Reference
Genesis 1              31    791   25.5         2m 38s
Genesis 2              25    639   25.6          2m 7s
Genesis 3              24    683   28.5         2m 16s
Genesis 4              26    594   22.8         1m 58s
Genesis 5              32    427   13.3         1m 25s
Genesis 6              22    531   24.1         1m 46s
Genesis 7              24    543   22.6         1m 48s
Genesis 8              22    549   25.0         1m 49s
Genesis 9              29    619   21.3          2m 3s
Genesis 10             32    427   13.3         1m 25s
Genesis 11             32    573   17.9         1m 54s
Genesis 12             20    502   25.1         1m 40s
Genesis 13             18    427   23.7         1m 25s
Genesis 14             24    581   24.2         1m 56s
Genesis 15             21    445   21.2         1m 29s
Genesis 16             16    402   25.1         1m 20s
Genesis 17             27    652   24.1         2m 10s
Genesis 18             33    826   25.0         2m 45s
Genesis 19             38   1024   26.9         3m 24s
Genesis 20             18    495   27.5         1m 39s
Genesis 21             34    757   22.3         2m 31s
Genesis 22             24    584   24.3         1m 56s
Genesis 23             20    489   24.4         1m 37s
Genesis 24             67   1728   25.8         5m 45s
Genesis 25             34    630   18.5          2m 6s
Genesis 26             35    839   24.0         2m 47s
Genesis 27             46   1196   26.0         3m 59s
Genesis 28             22    598   27.2         1m 59s
Genesis 29             35    803   22.9         2m 40s
Genesis 30             43    978   22.7         3m 15s
Genesis 31             55   1372   24.9         4m 34s
Genesis 32             32    773   24.2         2m 34s
Genesis 33             20    490   24.5         1m 38s
Genesis 34             31    762   24.6         2m 32s
Genesis 35             29    630   21.7          2m 6s
Genesis 36             43    769   17.9         2m 33s
Genesis 37             36    898   24.9         2m 59s
Genesis 38             30    771   25.7         2m 34s
Genesis 39             23    631   27.4          2m 6s
Genesis 40             23    518   22.5         1m 43s
Genesis 41             57   1313   23.0         4m 22s
Genesis 42             38    984   25.9         3m 16s
Genesis 43             34    911   26.8          3m 2s
Genesis 44             34    857   25.2         2m 51s
Genesis 45             28    714   25.5         2m 22s
Genesis 46             34    711   20.9         2m 22s
Genesis 47             31    942   30.4          3m 8s
Genesis 48             22    632   28.7          2m 6s
Genesis 49             33    721   21.8         2m 24s
Genesis 50             26    666   25.6         2m 13s
Exodus 1               22    413   18.8         1m 22s
Exodus 2               25    613   24.5          2m 2s
Exodus 3               22    734   33.4         2m 26s
Exodus 4               31    833   26.9         2m 46s
Exodus 5               23    592   25.7         1m 58s
Exodus 6               30    689   23.0         2m 17s
Exodus 7               25    659   26.4         2m 11s
Exodus 8               32    909   28.4          3m 1s
Exodus 9               35    969   27.7         3m 13s
Exodus 10              29    861   29.7         2m 52s
Exodus 11              10    307   30.7          1m 1s
Exodus 12              51   1387   27.2         4m 37s
Exodus 13              22    646   29.4          2m 9s
Exodus 14              31    861   27.8         2m 52s
Exodus 15              27    665   24.6         2m 13s
Exodus 16              36    994   27.6         3m 18s
Exodus 17              16    452   28.2         1m 30s
Exodus 18              27    698   25.9         2m 19s
Exodus 19              25    667   26.7         2m 13s
Exodus 20              26    573   22.0         1m 54s
Exodus 21              36    861   23.9         2m 52s
Exodus 22              31    776   25.0         2m 35s
Exodus 23              33    840   25.5         2m 48s
Exodus 24              18    479   26.6         1m 35s
Exodus 25              40    875   21.9         2m 55s
Exodus 26              37    890   24.1         2m 58s
Exodus 27              21    549   26.1         1m 49s
Exodus 28              43   1105   25.7         3m 41s
Exodus 29              46   1273   27.7         4m 14s
Exodus 30              38    898   23.6         2m 59s
Exodus 31              18    406   22.6         1m 21s
Exodus 32              35   1062   30.3         3m 32s
Exodus 33              23    680   29.6         2m 16s
Exodus 34              35    977   27.9         3m 15s
Exodus 35              35    765   21.9         2m 33s
Exodus 36              38    835   22.0         2m 47s
Exodus 37              29    667   23.0         2m 13s
Exodus 38              31    779   25.1         2m 35s
Exodus 39              43    991   23.0         3m 18s
Exodus 40              38    775   20.4         2m 35s
Leviticus 1            17    486   28.6         1m 37s
Leviticus 2            16    446   27.9         1m 29s
Leviticus 3            17    477   28.1         1m 35s
Leviticus 4            35   1115   31.9         3m 43s
Leviticus 5            19    690   36.3         2m 18s
Leviticus 6            30    830   27.7         2m 46s
Leviticus 7            38    964   25.4         3m 12s
Leviticus 8            36    987   27.4         3m 17s
Leviticus 9            24    621   25.9          2m 4s
Leviticus 10           20    622   31.1          2m 4s
Leviticus 11           47   1035   22.0         3m 27s
Leviticus 12            8    245   30.6         0m 49s
Leviticus 13           59   1766   29.9         5m 53s
Leviticus 14           57   1631   28.6         5m 26s
Leviticus 15           33    897   27.2         2m 59s
Leviticus 16           34   1121   33.0         3m 44s
Leviticus 17           16    526   32.9         1m 45s
Leviticus 18           30    648   21.6          2m 9s
Leviticus 19           37    909   24.6          3m 1s
Leviticus 20           27    791   29.3         2m 38s
Leviticus 21           24    571   23.8         1m 54s
Leviticus 22           33    862   26.1         2m 52s
Leviticus 23           44   1205   27.4          4m 1s
Leviticus 24           23    508   22.1         1m 41s
Leviticus 25           55   1430   26.0         4m 46s
Leviticus 26           46   1217   26.5          4m 3s
Leviticus 27           34    893   26.3         2m 58s
Numbers 1              54   1094   20.3         3m 38s
Numbers 2              34    590   17.4         1m 58s
Numbers 3              51   1162   22.8         3m 52s
Numbers 4              49   1281   26.1         4m 16s
Numbers 5              31    905   29.2          3m 1s
Numbers 6              27    731   27.1         2m 26s
Numbers 7              89   1871   21.0         6m 14s
Numbers 8              26    684   26.3         2m 16s
Numbers 9              23    677   29.4         2m 15s
Numbers 10             36    851   23.6         2m 50s
Numbers 11             35   1019   29.1         3m 23s
Numbers 12             16    365   22.8         1m 13s
Numbers 13             33    722   21.9         2m 24s
Numbers 14             45   1183   26.3         3m 56s
Numbers 15             41   1014   24.7         3m 22s
Numbers 16             50   1285   25.7         4m 17s
Numbers 17             13    309   23.8          1m 1s
Numbers 18             32   1044   32.6         3m 28s
Numbers 19             22    670   30.5         2m 14s
Numbers 20             29    768   26.5         2m 33s
Numbers 21             35    899   25.7         2m 59s
Numbers 22             41   1142   27.9         3m 48s
Numbers 23             30    729   24.3         2m 25s
Numbers 24             25    614   24.6          2m 2s
Numbers 25             18    442   24.6         1m 28s
Numbers 26             65   1295   19.9         4m 19s
Numbers 27             23    570   24.8         1m 54s
Numbers 28             31    740   23.9         2m 28s
Numbers 29             40    894   22.4         2m 58s
Numbers 30             16    493   30.8         1m 38s
Numbers 31             54   1077   19.9         3m 35s
Numbers 32             42   1008   24.0         3m 21s
Numbers 33             56    950   17.0         3m 10s
Numbers 34             29    587   20.2         1m 57s
Numbers 35             34    946   27.8          3m 9s
Numbers 36             13    432   33.2         1m 26s
Deuteronomy 1          46   1236   26.9          4m 7s
Deuteronomy 2          37   1017   27.5         3m 23s
Deuteronomy 3          29    837   28.9         2m 47s
Deuteronomy 4          49   1498   30.6         4m 59s
Deuteronomy 5          33    910   27.6          3m 2s
Deuteronomy 6          25    652   26.1         2m 10s
Deuteronomy 7          26    834   32.1         2m 46s
Deuteronomy 8          20    551   27.6         1m 50s
Deuteronomy 9          29    958   33.0         3m 11s
Deuteronomy 10         22    589   26.8         1m 57s
Deuteronomy 11         32    925   28.9          3m 5s
Deuteronomy 12         32   1042   32.6         3m 28s
Deuteronomy 13         18    591   32.8         1m 58s
Deuteronomy 14         29    659   22.7         2m 11s
Deuteronomy 15         23    682   29.7         2m 16s
Deuteronomy 16         22    702   31.9         2m 20s
Deuteronomy 17         20    699   35.0         2m 19s
Deuteronomy 18         22    580   26.4         1m 56s
Deuteronomy 19         21    585   27.9         1m 57s
Deuteronomy 20         20    615   30.8          2m 2s
Deuteronomy 21         23    718   31.2         2m 23s
Deuteronomy 22         30    868   28.9         2m 53s
Deuteronomy 23         25    655   26.2         2m 11s
Deuteronomy 24         22    662   30.1         2m 12s
Deuteronomy 25         19    556   29.3         1m 51s
Deuteronomy 26         19    658   34.6         2m 11s
Deuteronomy 27         26    580   22.3         1m 56s
Deuteronomy 28         68   1987   29.2         6m 37s
Deuteronomy 29         29    824   28.4         2m 44s
Deuteronomy 30         20    640   32.0          2m 8s
Deuteronomy 31         30   1000   33.3         3m 20s
Deuteronomy 32         52   1269   24.4         4m 13s
Deuteronomy 33         29    722   24.9         2m 24s
Deuteronomy 34         12    317   26.4          1m 3s
Joshua 1               18    558   31.0         1m 51s
Joshua 2               24    750   31.2         2m 30s
Joshua 3               17    547   32.2         1m 49s
Joshua 4               24    670   27.9         2m 14s
Joshua 5               15    537   35.8         1m 47s
Joshua 6               27    881   32.6         2m 56s
Joshua 7               26    888   34.2         2m 57s
Joshua 8               35   1151   32.9         3m 50s
Joshua 9               27    768   28.4         2m 33s
Joshua 10              43   1345   31.3         4m 29s
Joshua 11              23    686   29.8         2m 17s
Joshua 12              24    470   19.6         1m 34s
Joshua 13              33    840   25.5         2m 48s
Joshua 14              15    464   30.9         1m 32s
Joshua 15              63    898   14.3         2m 59s
Joshua 16              10    254   25.4         0m 50s
Joshua 17              18    615   34.2          2m 2s
Joshua 18              28    742   26.5         2m 28s
Joshua 19              51    847   16.6         2m 49s
Joshua 20               9    300   33.3          1m 0s
Joshua 21              45    937   20.8          3m 7s
Joshua 22              34   1293   38.0         4m 18s
Joshua 23              16    538   33.6         1m 47s
Joshua 24              33   1014   30.7         3m 22s
Judges 1               36    946   26.3          3m 9s
Judges 2               23    677   29.4         2m 15s
Judges 3               31    834   26.9         2m 46s
Judges 4               24    732   30.5         2m 26s
Judges 5               31    701   22.6         2m 20s
Judges 6               40   1283   32.1         4m 16s
Judges 7               25    902   36.1          3m 0s
Judges 8               35    968   27.7         3m 13s
Judges 9               57   1580   27.7         5m 16s
Judges 10              18    457   25.4         1m 31s
Judges 11              40   1175   29.4         3m 55s
Judges 12              15    384   25.6         1m 16s
Judges 13              25    733   29.3         2m 26s
Judges 14              20    680   34.0         2m 16s
Judges 15              20    636   31.8          2m 7s
Judges 16              31   1102   35.5         3m 40s
Judges 17              13    387   29.8         1m 17s
Judges 18              31   1009   32.5         3m 21s
Judges 19              30   1052   35.1         3m 30s
Judges 20              48   1372   28.6         4m 34s
Judges 21              25    702   28.1         2m 20s
Ruth 1                 22    619   28.1          2m 3s
Ruth 2                 23    721   31.3         2m 24s
Ruth 3                 18    473   26.3         1m 34s
Ruth 4                 22    624   28.4          2m 4s
1 Samuel 1             28    758   27.1         2m 31s
1 Samuel 2             36   1113   30.9         3m 42s
1 Samuel 3             21    527   25.1         1m 45s
1 Samuel 4             22    696   31.6         2m 19s
1 Samuel 5             12    427   35.6         1m 25s
1 Samuel 6             21    735   35.0         2m 27s
1 Samuel 7             17    509   29.9         1m 41s
1 Samuel 8             22    527   24.0         1m 45s
1 Samuel 9             27    940   34.8          3m 8s
1 Samuel 10            27    848   31.4         2m 49s
1 Samuel 11            15    482   32.1         1m 36s
1 Samuel 12            25    781   31.2         2m 36s
1 Samuel 13            23    683   29.7         2m 16s
1 Samuel 14            52   1582   30.4         5m 16s
1 Samuel 15            35    953   27.2         3m 10s
1 Samuel 16            23    654   28.4         2m 10s
1 Samuel 17            58   1661   28.6         5m 32s
1 Samuel 18            30    794   26.5         2m 38s
1 Samuel 19            24    674   28.1         2m 14s
1 Samuel 20            42   1217   29.0          4m 3s
1 Samuel 21            15    483   32.2         1m 36s
1 Samuel 22            23    737   32.0         2m 27s
1 Samuel 23            29    801   27.6         2m 40s
1 Samuel 24            22    646   29.4          2m 9s
1 Samuel 25            44   1343   30.5         4m 28s
1 Samuel 26            25    830   33.2         2m 46s
1 Samuel 27            12    380   31.7         1m 16s
1 Samuel 28            25    780   31.2         2m 36s
1 Samuel 29            11    422   38.4         1m 24s
1 Samuel 30            31    846   27.3         2m 49s
1 Samuel 31            13    339   26.1          1m 7s
2 Samuel 1             27    675   25.0         2m 15s
2 Samuel 2             32    865   27.0         2m 53s
2 Samuel 3             39   1119   28.7         3m 43s
2 Samuel 4             12    414   34.5         1m 22s
2 Samuel 5             25    597   23.9         1m 59s
2 Samuel 6             23    671   29.2         2m 14s
2 Samuel 7             29    827   28.5         2m 45s
2 Samuel 8             18    420   23.3         1m 24s
2 Samuel 9             13    392   30.2         1m 18s
2 Samuel 10            19    575   30.3         1m 55s
2 Samuel 11            27    771   28.6         2m 34s
2 Samuel 12            31    975   31.5         3m 15s
2 Samuel 13            39   1106   28.4         3m 41s
2 Samuel 14            33   1077   32.6         3m 35s
2 Samuel 15            37   1051   28.4         3m 30s
2 Samuel 16            23    702   30.5         2m 20s
2 Samuel 17            29    892   30.8         2m 58s
2 Samuel 18            33   1084   32.8         3m 36s
2 Samuel 19            43   1421   33.0         4m 44s
2 Samuel 20            26    816   31.4         2m 43s
2 Samuel 21            22    772   35.1         2m 34s
2 Samuel 22            51    878   17.2         2m 55s
2 Samuel 23            39    851   21.8         2m 50s
2 Samuel 24            25    844   33.8         2m 48s
1 Kings 1              53   1447   27.3         4m 49s
1 Kings 2              46   1437   31.2         4m 47s
1 Kings 3              28    822   29.4         2m 44s
1 Kings 4              34    661   19.4         2m 12s
1 Kings 5              18    499   27.7         1m 39s
1 Kings 6              38    976   25.7         3m 15s
1 Kings 7              51   1397   27.4         4m 39s
1 Kings 8              66   2045   31.0         6m 49s
1 Kings 9              28    787   28.1         2m 37s
1 Kings 10             29    799   27.6         2m 39s
1 Kings 11             43   1237   28.8          4m 7s
1 Kings 12             33    995   30.2         3m 19s
1 Kings 13             34   1093   32.1         3m 38s
1 Kings 14             31    934   30.1          3m 6s
1 Kings 15             34    946   27.8          3m 9s
1 Kings 16             34   1015   29.9         3m 23s
1 Kings 17             24    653   27.2         2m 10s
1 Kings 18             46   1354   29.4         4m 30s
1 Kings 19             21    730   34.8         2m 26s
1 Kings 20             43   1372   31.9         4m 34s
1 Kings 21             29    856   29.5         2m 51s
1 Kings 22             53   1465   27.6         4m 53s
2 Kings 1              18    634   35.2          2m 6s
2 Kings 2              25    835   33.4         2m 47s
2 Kings 3              27    810   30.0         2m 42s
2 Kings 4              44   1295   29.4         4m 19s
2 Kings 5              27    932   34.5          3m 6s
2 Kings 6              33   1004   30.4         3m 20s
2 Kings 7              20    784   39.2         2m 36s
2 Kings 8              29    935   32.2          3m 7s
2 Kings 9              37   1172   31.7         3m 54s
2 Kings 10             36   1179   32.8         3m 55s
2 Kings 11             21    712   33.9         2m 22s
2 Kings 12             21    690   32.9         2m 18s
2 Kings 13             25    771   30.8         2m 34s
2 Kings 14             29    859   29.6         2m 51s
2 Kings 15             38   1104   29.1         3m 40s
2 Kings 16             20    658   32.9         2m 11s
2 Kings 17             41   1226   29.9          4m 5s
2 Kings 18             37   1181   31.9         3m 56s
2 Kings 19             37   1079   29.2         3m 35s
2 Kings 20             21    652   31.0         2m 10s
2 Kings 21             26    753   29.0         2m 30s
2 Kings 22             20    696   34.8         2m 19s
2 Kings 23             37   1433   38.7         4m 46s
2 Kings 24             20    573   28.6         1m 54s
2 Kings 25             30    945   31.5          3m 9s
1 Chronicles 1         54    582   10.8         1m 56s
1 Chronicles 2         55    744   13.5         2m 28s
1 Chronicles 3         24    308   12.8          1m 1s
1 Chronicles 4         43    744   17.3         2m 28s
1 Chronicles 5         26    594   22.8         1m 58s
1 Chronicles 6         81   1140   14.1         3m 48s
1 Chronicles 7         40    695   17.4         2m 19s
1 Chronicles 8         40    419   10.5         1m 23s
1 Chronicles 9         44    871   19.8         2m 54s
1 Chronicles 10        14    354   25.3         1m 10s
1 Chronicles 11        47    926   19.7          3m 5s
1 Chronicles 12        40    837   20.9         2m 47s
1 Chronicles 13        14    376   26.9         1m 15s
1 Chronicles 14        17    335   19.7          1m 7s
1 Chronicles 15        29    663   22.9         2m 12s
1 Chronicles 16        43    807   18.8         2m 41s
1 Chronicles 17        27    739   27.4         2m 27s
1 Chronicles 18        17    397   23.4         1m 19s
1 Chronicles 19        19    580   30.5         1m 56s
1 Chronicles 20         8    275   34.4         0m 55s
1 Chronicles 21        30    882   29.4         2m 56s
1 Chronicles 22        19    579   30.5         1m 55s
1 Chronicles 23        32    625   19.5          2m 5s
1 Chronicles 24        31    502   16.2         1m 40s